name: Aikido Security Check for Dependency scanning
on:
  pull_request:
    branches:
      - '*'

jobs:
  aikido-security:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout code
        uses: actions/checkout@v3

      - name: Detect new vulnerabilities
        uses: AikidoSec/github-actions-workflow@v1.0.8
        with:
            secret-key: AIK_CI_0CBLxaHiYjWiNt2e4fEOabFOm0SO1VTk6aLq46Okapj11zOfArYm895F3DruMYCX
            fail-on-timeout: true
            fail-on-dependency-scan: true
            minimum-severity: 'LOW'
            timeout-seconds: 180
            post-scan-status-comment: false
